name = "VTUFileHandler"
uuid = "6e9f8158-41af-4c42-b493-3202dfdd0db4"
authors = [Max Bittens <maximilian.bittens@bgr.de>]
license = "MIT"
version = "0.0.4"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"

[compat]
julia = "1"
